package com.as.xiajue.picturebing.database.genUtils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.as.xiajue.picturebing.bean.ImageBean;

import com.as.xiajue.picturebing.database.genUtils.ImageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageBeanDaoConfig;

    private final ImageBeanDao imageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageBeanDaoConfig = daoConfigMap.get(ImageBeanDao.class).clone();
        imageBeanDaoConfig.initIdentityScope(type);

        imageBeanDao = new ImageBeanDao(imageBeanDaoConfig, this);

        registerDao(ImageBean.class, imageBeanDao);
    }
    
    public void clear() {
        imageBeanDaoConfig.clearIdentityScope();
    }

    public ImageBeanDao getImageBeanDao() {
        return imageBeanDao;
    }

}
